// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(in *jlexer.Lexer, out *Report) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = int64(in.Int64())
		case "area":
			(out.Area).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(out *jwriter.Writer, in Report) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		(in.Area).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Report) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Report) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Report) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Report) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels(l, v)
}
func easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(in *jlexer.Lexer, out *License) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "digAllowed":
			out.DigAllowed = int64(in.Int64())
		case "digUsed":
			out.DigUsed = int64(in.Int64())
		case "id":
			out.ID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(out *jwriter.Writer, in License) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"digAllowed\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.DigAllowed))
	}
	{
		const prefix string = ",\"digUsed\":"
		out.RawString(prefix)
		out.Int64(int64(in.DigUsed))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v License) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v License) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *License) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *License) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels1(l, v)
}
func easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(in *jlexer.Lexer, out *Error) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int32(in.Int32())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(out *jwriter.Writer, in Error) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Error) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Error) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Error) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Error) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels2(l, v)
}
func easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(in *jlexer.Lexer, out *Dig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "depth":
			out.Depth = int64(in.Int64())
		case "licenseID":
			out.LicenseID = int64(in.Int64())
		case "posX":
			out.PosX = int64(in.Int64())
		case "posY":
			out.PosY = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(out *jwriter.Writer, in Dig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"depth\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Depth))
	}
	{
		const prefix string = ",\"licenseID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LicenseID))
	}
	{
		const prefix string = ",\"posX\":"
		out.RawString(prefix)
		out.Int64(int64(in.PosX))
	}
	{
		const prefix string = ",\"posY\":"
		out.RawString(prefix)
		out.Int64(int64(in.PosY))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Dig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Dig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Dig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Dig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels3(l, v)
}
func easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(in *jlexer.Lexer, out *Area) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "posX":
			out.PosX = int64(in.Int64())
		case "posY":
			out.PosY = int64(in.Int64())
		case "sizeX":
			out.SizeX = int64(in.Int64())
		case "sizeY":
			out.SizeY = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(out *jwriter.Writer, in Area) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"posX\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.PosX))
	}
	{
		const prefix string = ",\"posY\":"
		out.RawString(prefix)
		out.Int64(int64(in.PosY))
	}
	if in.SizeX != 0 {
		const prefix string = ",\"sizeX\":"
		out.RawString(prefix)
		out.Int64(int64(in.SizeX))
	}
	if in.SizeY != 0 {
		const prefix string = ",\"sizeY\":"
		out.RawString(prefix)
		out.Int64(int64(in.SizeY))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Area) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Area) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Area) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Area) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRomanIschenkoGoldenRushMailruInternalHttpModels4(l, v)
}
